Dockerfile
README.md

Add tt-rss-newsplus-plugin

---

README.md
configure-db.php

feat: add env to set session expire time

---

Dockerfile

feat: add new plugin: options_per_feed

---

Dockerfile
Dockerfile.dev
docker-compose.dev.yml
docs/README.md
docs/zh/README.md
hooks/build
hooks/post_push

feat: add tags to docker images

---

docker-compose.dev.yml
docs/README.md
docs/zh/README.md
src/configure-db.php

Add single user mode support

---

Dockerfile
Dockerfile.dev

https://github.com/curl/curl/issues/4357

fix: curl_multi_poll: symbol not found

---

docker-compose.dev.yml
docker-compose.yml
docs/README.md
docs/zh/README.md
package.json
src/configure-db.php

fix: remove DB_NAME but initialize pg_trgm extension

---

Dockerfile.arm32v7
docker-compose.arm32v7.yml
docker-compose.dev.yml
docs/README.md
hooks/post_checkout
hooks/pre_build

feat: add support for the arm32v7 architecture 

---

docker-compose.legacy.yml
docs/README.md
docs/zh/README.md

breaking change: migrate from sameersbn/postgresql to postgres:alpine

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8
Dockerfile.dev

fix: update libiconv as the default version is too low 

---

Dockerfile.arm64v8
hooks/post_checkout
hooks/pre_build

fix: qemu static library for arm64v8

---

docs/README.md
src/configure-db.php

Juste exposed two more settings via environment variables.

Support LOG_DESTINATION env var

---

docker-compose.yml
docs/README.md
docs/zh/README.md
src/configure-db.php

feat: add env FEED_LOG_QUIET to set logging to quiet

---

Dockerfile
docker-compose.yml
docker-entrypoint.sh
docs/README.md
docs/zh/README.md

feat: allow the use of non-'80, 443' ports

---

docker-entrypoint.sh

fix: reset urlhelper.php upon each restart

---

docker-compose.yml

fix: mercury public access

---

Dockerfile
src/initialize.php
src/ttrss.nginx.conf

TT-RSS [supports this natively](https://git.tt-rss.org/fox/ttrss-docker-compose/src/branch/master/app/config.php-xaccel), and it helps performance: https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/
What I did is almost just copying from https://git.tt-rss.org/fox/ttrss-docker-compose. And it works well.

feat: add nginx x-accel header plugin

---

docs/README.md
docs/zh/README.md

And trigger docker build to resolve DigitalDJ/tinytinyrss-fever-plugin#21 :)

chore(doc): update reeder from 4 to 5

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
Dockerfile
docker-entrypoint.sh
package.json
src/initialize.php

Fix #267 
I've also checked the theory about ALLOW_PORTS, but I don't think there's any change in behavior for urlhelper.php yet

feat: transition into optional config.php

---

src/initialize.php

fix: DISABLE_USER_IN_DAYS

---

Dockerfile

fix: missing php8-zip for restoring starred feeds

---

src/initialize.php

for:
- [ttrss-mailer-smtp](https://git.tt-rss.org/fox/ttrss-mailer-smtp)
- [ttrss-nginx-xaccel](https://git.tt-rss.org/fox/ttrss-nginx-xaccel)
- [ttrss-perceptual-image-hash](https://git.tt-rss.org/fox/ttrss-perceptual-image-hash)
fix #339

fix: add missing envs

---

docker-entrypoint.sh
src/initialize.php

fix #479
due to https://gitlab.tt-rss.org/tt-rss/tt-rss/-/commit/865ecc87963dc3b26e66296616eef2a1cc41ac3f?page=3 renaming

fix: UrlHelper.php did not match any file

---

src/ttrss.nginx.conf

fix: nginx return 404 for hidden files and directories

---

Dockerfile

Reverts HenryQW/Awesome-TTRSS#515
Alpine 3.20 does not have php8.1

revert: "chore(deps): bump alpine from 3.19 to 3.20"

---

Dockerfile
docs/README.md
docs/zh/README.md

Resolving a typo in the docker file which prevents FreshAPI from functioning. Adding English and Chinese documentation.

Typo Correction, English & Chinese Documentation for FreshAPI

---

.github/workflows/build-nightly-release.yml
.github/workflows/build-release.yml
.github/workflows/build-test.yml
Dockerfile
docker-compose.dev.yml

- Consolidated multiple `RUN` commands into a single one to reduce image layers
- Added package `tzdata`, fix #461
- Added Feedlish theme, fix #468
- Removed `php8x-pgsql`, follow https://gitlab.tt-rss.org/tt-rss/tt-rss/-/merge_requests/85/diffs

feat: reduce docker image layers

---

docs/index.md
docs/zh/index.md
src/initialize.php

- reorder envs
- remove `ICONS_URL` https://gitlab.tt-rss.org/tt-rss/tt-rss/-/commit/d361c1c65d912358c9a9eee1db1992ff532eb299
- update envs docs link

feat: add missing envs

---

docker-compose.yml

fix: update docker compose cache mapping
